[package]
name = "cabaret-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "cab"
path = "src/main.rs"

[dependencies]
cabaret-lib.workspace = true
clap.workspace = true
clap_complete.workspace = true

[lints]
workspace = true
