[package]
name = "cabaret-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

# TODO-someday(joel): move napi to separate crate, cdylib adds 150ms to build
[lib]
crate-type = ["lib", "cdylib"]

[features]
napi = ["dep:napi", "dep:napi-derive", "dep:napi-build", "cabaret-types/napi", "cabaret-agents/napi"]

[dependencies]
cabaret-agents.workspace = true
cabaret-transaction.workspace = true
cabaret-types.workspace = true
gix.workspace = true
napi = { workspace = true, optional = true }
napi-derive = { workspace = true, optional = true }
nonempty-collections.workspace = true

[dev-dependencies]
expect-test.workspace = true
tempfile.workspace = true

[build-dependencies]
napi-build = { workspace = true, optional = true }

[lints]
workspace = true
